
// Objective-C API for talking to the following Go packages
//
//	golang.org/x/mobile/example/signer
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Signer_FRAMEWORK_H__
#define __Signer_FRAMEWORK_H__

#include "Signer.objc.h"
#include "universe.objc.h"

#endif
