// Objective-C API for talking to golang.org/x/mobile/example/signer Go package.
//   gobind -lang=objc golang.org/x/mobile/example/signer
//
// File is generated by gobind. Do not edit.

#ifndef __Signer_H__
#define __Signer_H__

@import Foundation;
#include "Universe.objc.h"


@interface Signer : NSObject
+ (NSString*) signature;
+ (void) setSignature:(NSString*)v;

@end

FOUNDATION_EXPORT void SignerGetSignature(NSString* key, NSString* transaction);

FOUNDATION_EXPORT NSData* SignerSign(NSData* private, NSData* data, NSError** error);

#endif
